# Generated by Django 3.0.8 on 2020-07-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20200723_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='dt_transaction',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='observation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
