# Generated by Django 3.0.8 on 2020-07-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_auto_20200723_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='dt_transaction',
            field=models.DateTimeField(),
        ),
    ]
